/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package be.tulipemoutarde.headphones;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="Headphones", id="be.tulipemoutarde.headphones")
public class HeadphonesModule extends KrollModule
{
	// JNI
	static {
		System.loadLibrary("headphones");
	}

	// Native JNI method signatures
	public native int silence();

	// Standard Debugging variables
	private static final String LCAT = "HeadphonesModule";
	private static final boolean DBG = TiConfig.LOGD;

	public HeadphonesModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app){
		Log.d(LCAT, "inside onAppCreate");
	}

	// Methods
	@Kroll.method
	public String javaSilence(){
		silence(); // JNI call
		return "It worked !";
	}
}

